// leave off @2x/@3x
const images = {
  logo: require('../Images/ir.png'),
  clearLogo: require('../Images/top_logo.png'),
  launch: require('../Images/launch-icon.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/ignite_logo.png'),
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backButton: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),

  // qiscus chat
  qiscusDelete: require('../Images/Qiscus/delete.png'),
  qiscusFailed: require('../Images/Qiscus/failed-send.png'),
  qiscusAttachment: require('../Images/Qiscus/ic_attachment.png'),
  qiscusBack: require('../Images/Qiscus/ic_back.png'),
  qiscusCheck: require('../Images/Qiscus/ic_back.png'),
  qiscusContact: require('../Images/Qiscus/ic_contact.png'),
  qiscusDelivered: require('../Images/Qiscus/ic_delivered.png'),
  qiscusEdit: require('../Images/Qiscus/ic_edit.png'),
  qiscusFileAttachment: require('../Images/Qiscus/ic_file_attachment.png'),
  qiscusId: require('../Images/Qiscus/ic_id.png'),
  qiscusImageAttachment: require('../Images/Qiscus/ic_image_attachment.png'),
  qiscusMagnifier: require('../Images/Qiscus/ic_magnifier.png'),
  qiscusNewChatGroup: require('../Images/Qiscus/ic_new_chat-group.png'),
  qiscusNewChat: require('../Images/Qiscus/ic_new_chat.png'),
  qiscusNext: require('../Images/Qiscus/ic_next.png'),
  qiscusRead: require('../Images/Qiscus/ic_read.png'),
  qiscusSelected: require('../Images/Qiscus/ic_selected.png'),
  qiscusSend: require('../Images/Qiscus/ic_send.png'),
  qiscusSending: require('../Images/Qiscus/ic_sending.png'),
  qiscusImgSendMessage: require('../Images/Qiscus/img_send_message.png'),
}

export default images
